"""时间戳

Revision ID: 06e4fe075a8a
Revises: 5f31fbe5b118
Create Date: 2020-03-16 17:24:28.430492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06e4fe075a8a'
down_revision = '5f31fbe5b118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urltasks', sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
    op.add_column('urltasks', sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'))
    op.drop_column('urltasks', 'updateTime')
    op.drop_column('urltasks', 'createTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urltasks', sa.Column('createTime', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('urltasks', sa.Column('updateTime', mysql.TIMESTAMP(), nullable=False))
    op.drop_column('urltasks', 'update_time')
    op.drop_column('urltasks', 'create_time')
    # ### end Alembic commands ###
