"""设置表编码

Revision ID: 165b97a49842
Revises: dced291038e8
Create Date: 2020-02-24 16:39:16.948414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165b97a49842'
down_revision = 'dced291038e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
