"""增加star表

Revision ID: 1a98818970ba
Revises: b6f64d9024cb
Create Date: 2020-02-22 17:40:12.684035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a98818970ba'
down_revision = 'b6f64d9024cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stars',
    sa.Column('sid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=30), nullable=True),
    sa.Column('if_crawl', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stars')
    # ### end Alembic commands ###
