"""部分修改为Text类型

Revision ID: 2fb061d83ab3
Revises: 8fc46bdf455c
Create Date: 2020-02-24 16:14:50.740582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb061d83ab3'
down_revision = '8fc46bdf455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
