"""修改字段属性JSON

Revision ID: 406407f82345
Revises: 51c3b71d8275
Create Date: 2020-02-24 18:21:11.419965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406407f82345'
down_revision = '51c3b71d8275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
