"""时间戳更新

Revision ID: 40a2e346d423
Revises: 25e835bc50c4
Create Date: 2020-03-16 16:49:11.223029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a2e346d423'
down_revision = '25e835bc50c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
