"""修改字段属性

Revision ID: 51c3b71d8275
Revises: 8c82f23f4318
Create Date: 2020-02-24 17:39:12.615404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c3b71d8275'
down_revision = '8c82f23f4318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
