"""时间戳更新

Revision ID: 5f31fbe5b118
Revises: 40a2e346d423
Create Date: 2020-03-16 16:53:46.427622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f31fbe5b118'
down_revision = '40a2e346d423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urltasks', sa.Column('createtime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
    op.add_column('urltasks', sa.Column('updatetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'))
    op.drop_column('urltasks', 'createTime')
    op.drop_column('urltasks', 'updateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urltasks', sa.Column('updateTime', mysql.TIMESTAMP(), nullable=False))
    op.add_column('urltasks', sa.Column('createTime', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_column('urltasks', 'updatetime')
    op.drop_column('urltasks', 'createtime')
    # ### end Alembic commands ###
