"""update

Revision ID: 87d0a9533217
Revises: 1a98818970ba
Create Date: 2020-02-24 10:41:26.447716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d0a9533217'
down_revision = '1a98818970ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
