"""去掉外键变为索引

Revision ID: 8c82f23f4318
Revises: 988b59c74c10
Create Date: 2020-02-24 17:16:10.209378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c82f23f4318'
down_revision = '988b59c74c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_aweme_id'), 'comments', ['aweme_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint('comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.create_index(op.f('ix_posts_user_id'), 'posts', ['user_id'], unique=False)
    op.drop_constraint('posts_ibfk_1', 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('posts_ibfk_1', 'posts', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_posts_user_id'), table_name='posts')
    op.create_foreign_key('comments_ibfk_1', 'comments', 'posts', ['aweme_id'], ['aweme_id'])
    op.create_foreign_key('comments_ibfk_2', 'comments', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_aweme_id'), table_name='comments')
    # ### end Alembic commands ###
