"""部分修改为Text类型

Revision ID: 8fc46bdf455c
Revises: b856735eff60
Create Date: 2020-02-24 15:57:22.580955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc46bdf455c'
down_revision = 'b856735eff60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dynamic_cover', sa.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('music_url', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('share_url', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'share_url')
    op.drop_column('users', 'avatar')
    op.drop_column('posts', 'music_url')
    op.drop_column('posts', 'dynamic_cover')
    # ### end Alembic commands ###
