"""修

Revision ID: 96f56ea7ef48
Revises: 83fa1cc5e075
Create Date: 2020-03-16 18:00:31.643015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f56ea7ef48'
down_revision = '83fa1cc5e075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
