"""update

Revision ID: b856735eff60
Revises: 87d0a9533217
Create Date: 2020-02-24 10:43:40.835726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b856735eff60'
down_revision = '87d0a9533217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
