"""设置表编码

Revision ID: bb02ac998b3b
Revises: 2fb061d83ab3
Create Date: 2020-02-24 16:27:16.233129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb02ac998b3b'
down_revision = '2fb061d83ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
