"""修改字段属性pickletype

Revision ID: c445b38dc52a
Revises: 406407f82345
Create Date: 2020-02-24 18:28:18.577053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c445b38dc52a'
down_revision = '406407f82345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
