"""增加爬取数量

Revision ID: dabe676fdafe
Revises: 96f56ea7ef48
Create Date: 2020-03-24 11:57:47.408124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabe676fdafe'
down_revision = '96f56ea7ef48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urltasks', sa.Column('num', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='爬取数量'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urltasks', 'num')
    # ### end Alembic commands ###
