"""设置表编码

Revision ID: dced291038e8
Revises: bb02ac998b3b
Create Date: 2020-02-24 16:35:29.658673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dced291038e8'
down_revision = 'bb02ac998b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
