"""修改字段属性

Revision ID: ecfd6eed2da8
Revises: dabe676fdafe
Create Date: 2020-03-24 20:47:23.655926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfd6eed2da8'
down_revision = 'dabe676fdafe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
