"""修改

Revision ID: ef10a5eea5d8
Revises: 06e4fe075a8a
Create Date: 2020-03-16 17:35:08.580462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef10a5eea5d8'
down_revision = '06e4fe075a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urltasks', sa.Column('crawl_count', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urltasks', 'crawl_count')
    # ### end Alembic commands ###
